version: "3.3"
services:
  web:
    build: ./docker
    hostname: localhost
    container_name: orfeusz-api-nginx
    environment:
      - APP_ENV=dev
    ports:
      - "6969:80"
      - "3001:3001"
      - "3002:3002"
    links:
      - mysql
    image: "universal"
    volumes:
      - .:/var/www/html
    tty: true
    network_mode: "bridge"
    restart: always

  mysql:
    image: mysql:latest
    restart: always
    container_name: orfeusz-api-mysql
    ports:
      - "10:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orfeusz
      - TZ=Europe/Warsaw
    network_mode: "bridge"
    volumes:
      - ./mysql-data:/var/lib/mysql
