<?php

namespace App\Repository;

use App\Entity\LiveChatConnection;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @extends ServiceEntityRepository<LiveChatConnection>
 *
 * @method LiveChatConnection|null find($id, $lockMode = null, $lockVersion = null)
 * @method LiveChatConnection|null findOneBy(array $criteria, array $orderBy = null)
 * @method LiveChatConnection[]    findAll()
 * @method LiveChatConnection[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class LiveChatConnectionRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, LiveChatConnection::class);
    }

    public function save(LiveChatConnection $entity, bool $flush = false): void
    {
        $this->getEntityManager()->persist($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }

    public function remove(LiveChatConnection $entity, bool $flush = false): void
    {
        $this->getEntityManager()->remove($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }

    public function getEntityManager(): EntityManagerInterface
    {
        return $this->_em; // TODO: Change the autogenerated stub
    }

//    /**
//     * @return LiveChatConnection[] Returns an array of LiveChatConnection objects
//     */
//    public function findByExampleField($value): array
//    {
//        return $this->createQueryBuilder('l')
//            ->andWhere('l.exampleField = :val')
//            ->setParameter('val', $value)
//            ->orderBy('l.id', 'ASC')
//            ->setMaxResults(10)
//            ->getQuery()
//            ->getResult()
//        ;
//    }

//    public function findOneBySomeField($value): ?LiveChatConnection
//    {
//        return $this->createQueryBuilder('l')
//            ->andWhere('l.exampleField = :val')
//            ->setParameter('val', $value)
//            ->getQuery()
//            ->getOneOrNullResult()
//        ;
//    }
}
