controllers:
    prefix: /api
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#DOCUMENTATION

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

#ADMIN

admin_login:
    path: /admin/login
    methods: [GET, POST]
    controller: App\Controller\Admin\SecurityController

admin_logout:
    path: /admin/logout
    methods: GET
    controller: App\Controller\Admin\SecurityController::logout

admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index